[package]
name = "fractals"
version = "0.0.1"
edition = "2021"

[dependencies]
# graphics library using webgpu
wgpu = "24.0"
# windowing
winit = { version = "0.29", features = ["rwh_05"] }
# lightweight async runtime
pollster = "0.3"
# simple (bitwise) type casting
bytemuck = { version = "1.16", features = [ "derive" ] }
# logging required (?) by wgpu
env_logger = "0.10"
log = "0.4"
